---
title: "NFL Data"
author: "Nate Lewis"
date: "2021-07-01"
output: github_document
---

```{r setup, echo=FALSE}
knitr::opts_chunk$set(echo = TRUE)

# change global notation
options(scipen = 9999,
        dplyr.summarise.inform = FALSE)
```

```{r data, echo=FALSE}
# load packages
library("nflfastR")
library("tidyverse")
library("knitr")
library("qs")
library("glue")

# source dependencies
source("./scripts/calculate_full_stats.R")

# play by play
future::plan("multisession")
pbp <- nflfastR::load_pbp(2010:2020, qs = TRUE) %>% 
  filter(season_type == "REG") %>% 
  progressr::with_progress()

# stats
overall_raw <- calculate_full_stats(pbp, weekly = FALSE) %>% 
    progressr::with_progress()
weekly_raw <- calculate_full_stats(pbp, weekly = TRUE) %>% 
    progressr::with_progress()

# load other
weekly_data <- read_csv("./data_output/weekly_data.csv")
season_data <- read_csv("./data_output/season_data.csv")
rosters <- read_csv("./data/rosters.csv") %>% 
  mutate(side_of_ball = ifelse(nw_position %in% c("QB", "RB", "WR/TE"), "OFF", "DEF"))

```

```{r}
colnames(weekly_data)
```

```{r}
colnames(season_data)
```

```{r player stats, echo=FALSE}
# join secondary data to stats
weekly_joined <- weekly_raw %>%
  left_join(rosters, by = c("player_id" = "gsis_id", "season")) %>%
  left_join(weekly_data, by = c("player_id", "season", "week", "recent_team")) %>%
  arrange(player_id, season, week)

overall_joined <- overall_raw %>%
  left_join(rosters, by = c("player_id" = "gsis_id", "season")) %>%
  left_join(season_data %>% select(-games), by = c("player_id", "season")) %>%
  arrange(-nw_pts) %>%
  group_by(nw_position, season) %>%
  mutate(nw_rk = 1:n()) %>%
  arrange(-fantasy_points) %>%
  mutate(std_rk = 1:n()) %>%
  ungroup() %>%
  arrange(-nw_pts) %>%
  group_by(season) %>%
  mutate(nw_rk_ovr = 1:n()) %>%
  arrange(-fantasy_points) %>%
  mutate(std_rk_ovr = 1:n()) %>%
  ungroup() %>%
  arrange(player_id, season)
```

Read in base stats with joined data from csv files and skip steps above
```{r eval=FALSE, include=FALSE}
weekly <- read_csv("./data_output/weekly_joined.csv")
overall <- read_csv("./data_output/overall_joined.csv")
players <- distinct(overall_joined$season)
```

```{r}
colnames(weekly_joined)
```

```{r}
colnames(overall_joined)
```

```{r columns}
# clean joined stats
primary_cols <- c(
  "player_id",
  "season",
  "week",
  "full_name",
  "recent_team",
  "position"
)

pass_cols <- c(
  "completions",
  "attempts",
  "passing_yards",
  "passing_tds",
  "interceptions",
  "sacks",
  "passing_air_yards",
  "passing_yards_after_catch",
  "passing_first_downs",
  "passing_epa",
  "dakota",
  "outside_rz_attempts",
  "rz_attempts",
  "ez_attempts",
  "ez_attempts_inside_rz",
  "ez_attempts_outside_rz",
  "deep_attempts",
  "short_attempts",
  "neutral_attempts",
  "garbadge_time_attempts",
  "rz_completion_pct",
  "ez_completion_pct",
  "deep_completion_pct",
  "short_completion_pct",
  "passing_yards_250",
  "passing_yards_300",
  "passing_yards_350",
  "passing_yards_400",
  "passing_tds_1",
  "passing_tds_20",
  "passing_tds_50",
  "int_tds"
)

rush_cols <-
  c(
    "carries",
    "rushing_yards",
    "rushing_tds",
    "rushing_first_downs",
    "rushing_epa",
    "outside_rz_carries",
    "rz_carries",
    "inside_ten_carries",
    "inside_five_carries",
    "neutral_carries",
    "garbadge_time_carries",
    "rushing_yards_90",
    "rushing_yards_100",
    "rushing_yards_150",
    "rushing_yards_200",
    "rushing_tds_1",
    "rushing_tds_10",
    "rushing_tds_30",
    "rushing_tds_50"
  )

rec_cols <- c(
  "receptions",
  "targets",
  "receiving_yards",
  "receiving_tds",
  "receiving_air_yards",
  "receiving_yards_after_catch",
  "receiving_first_downs",
  "receiving_epa",
  "outside_rz_targets",
  "rz_targets",
  "ez_targets",
  "ez_targets_inside_rz",
  "ez_targets_outside_rz",
  "deep_targets",
  "short_targets",
  "neutral_targets",
  "garbadge_time_targets",
  "adot",
  "catch_rate",
  "rz_catch_rate",
  "ez_catch_rate",
  "deep_catch_rate",
  "short_catch_rate",
  "receiving_yards_90",
  "receiving_yards_100",
  "receiving_yards_150",
  "receiving_yards_200",
  "receiving_tds_1",
  "receiving_tds_20",
  "receiving_tds_50"
)

combo_cols <-
  c(
    "special_teams_tds",
    "touches",
    "opportunities",
    "combo_yards_100",
    "combo_yards_150",
    "total_yards",
    "total_tds"
  )

stats_cols <- c(pass_cols, rush_cols, rec_cols, combo_cols)

fantasy_cols <- c(
  "pass_pts",
  "rec_pts",
  "rush_pts",
  "st_pts",
  "nw_rk",
  "nw_pts",
  "nw_rk_ovr",
  "std_rk",
  "fantasy_points",
  "std_rk_ovr"
)

snap_cols <- c(
  "total_snaps",
  "offense_snaps",
  "qual_snaps",
  "special_teams_snaps",
  "offense_snap_rate",
  "qual_snap_rate"
)

weekly_cols <-
  c(
    "game_id",
    "active_inactive",
    "game_designation",
    "started",
    "location",
    "opponent",
    "score",
    "team_result",
    "spread_line",
    "team_coach",
    "opp_coach"
  )

secondary_cols <-
  c(
    "player_name",
    "nw_position",
    "side_of_ball",
    "draft_year",
    "draft_round",
    "draft_pick"
  )

nw_cols <- c(
  "nw_pts",
  "nw_rk",
  "nw_rk_ovr")

roster_cols <- c(
  "full_name",
  "position",
  "nw_position",
  "birth_date",
  
  
```

```{r tidy weekly}
# clean joined stats
weekly <- weekly_joined[c(primary_cols, stats_cols, "nw_pts", "fantasy_points", weekly_cols, "nw_position", "side_of_ball")]

weekly <- weekly_joined %>%
  select(tidyselect::any_of(
    c(primary_cols))) 
      # basic info
      "season",
      "week",
      "full_name",
      "recent_team",
      "position",

      # passing
      "completions",
      "attempts",
      "passing_yards",
      "passing_tds",
      "interceptions",
      "sacks",
      "passing_air_yards",
      "passing_yards_after_catch",
      "passing_first_downs",
      "passing_epa",
      "dakota",
      "outside_rz_attempts",
      "rz_attempts",
      "ez_attempts",
      "ez_attempts_inside_rz",
      "ez_attempts_outside_rz",
      "deep_attempts",
      "short_attempts",
      "neutral_attempts",
      "garbadge_time_attempts",
      "rz_completion_pct",
      "ez_completion_pct",
      "deep_completion_pct",
      "short_completion_pct",
      "passing_yards_250",
      "passing_yards_300",
      "passing_yards_350",
      "passing_yards_400",
      "passing_tds_1",
      "passing_tds_20",
      "passing_tds_50",
      "int_tds",

      # rushing
      "carries",
      "rushing_yards",
      "rushing_tds",
      "rushing_first_downs",
      "rushing_epa",
      "outside_rz_carries",
      "rz_carries",
      "inside_ten_carries",
      "inside_five_carries",
      "neutral_carries",
      "garbadge_time_carries",
      "rushing_yards_90",
      "rushing_yards_100",
      "rushing_yards_150",
      "rushing_yards_200",
      "rushing_tds_1",
      "rushing_tds_10",
      "rushing_tds_30",
      "rushing_tds_50",

      # receiving stats
      "receptions",
      "targets",
      "receiving_yards",
      "receiving_tds",
      "receiving_air_yards",
      "receiving_yards_after_catch",
      "receiving_first_downs",
      "receiving_epa",
      "outside_rz_targets",
      "rz_targets",
      "ez_targets",
      "ez_targets_inside_rz",
      "ez_targets_outside_rz",
      "deep_targets",
      "short_targets",
      "neutral_targets",
      "garbadge_time_targets",
      "adot",
      "catch_rate",
      "rz_catch_rate",
      "ez_catch_rate",
      "deep_catch_rate",
      "short_catch_rate",
      "receiving_yards_90",
      "receiving_yards_100",
      "receiving_yards_150",
      "receiving_yards_200",
      "receiving_tds_1",
      "receiving_tds_20",
      "receiving_tds_50",

      # special teams
      "special_teams_tds",

      # combo
      "touches",
      "opportunities",
      "combo_yards_100",
      "combo_yards_150",
      "total_yards",
      "total_tds",

      # fantasy
      "pass_pts",
      "rec_pts",
      "rush_pts",
      "st_pts",
      "nw_pts",
      "fantasy_points",
      
      # snap data
      "total_snaps",
      "offense_snaps",
      "qual_snaps",
      "offense_snap_rate",
      "active_inactive",
      "game_designation",
      "started",
      
      # game data
      "game_id",
      "location",
      "opponent",
      "score",
      "team_result",
      "spread_line",
      "team_coach",
      "opp_coach",

      # secondary info
      "player_id",
      "player_name",
      "nw_position",
      "side_of_ball",
      "draft_year",
      "draft_round",
      "draft_pick"
    )
  )) %>%
  mutate(across(where(is.numeric), round, 2)) %>% 
  arrange(-season, player_id, week)
```

```{r tidy overall}
overall <- overall_joined %>%
  select(tidyselect::any_of(
    c(
      # basic info
      "season",
      "full_name",
      "recent_team",
      "position",
      "games",
      
      # passing
      "completions",
      "attempts",
      "passing_yards",
      "passing_tds",
      "interceptions",
      "sacks",
      "passing_air_yards",
      "passing_yards_after_catch",
      "passing_first_downs",
      "passing_epa",
      "dakota",
      "outside_rz_attempts",
      "rz_attempts",
      "ez_attempts",
      "ez_attempts_inside_rz",
      "ez_attempts_outside_rz",
      "deep_attempts",
      "short_attempts",
      "neutral_attempts",
      "garbadge_time_attempts",
      "rz_completion_pct",
      "ez_completion_pct",
      "deep_completion_pct",
      "short_completion_pct",
      "passing_yards_300",
      "passing_yards_350",
      "passing_yards_400",
      "passing_tds_1",
      "passing_tds_20",
      "passing_tds_50",
      "int_tds",
      
      # rushing
      "carries",
      "rushing_yards",
      "rushing_tds",
      "rushing_first_downs",
      "rushing_epa",
      "outside_rz_carries",
      "rz_carries",
      "inside_ten_carries",
      "inside_five_carries",
      "neutral_carries",
      "garbadge_time_carries",
      "rushing_yards_100",
      "rushing_yards_150",
      "rushing_yards_200",
      "rushing_tds_1",
      "rushing_tds_10",
      "rushing_tds_30",
      "rushing_tds_50",
      
      # receiving
      "receptions",
      "targets",
      "receiving_yards",
      "receiving_tds",
      "receiving_air_yards",
      "receiving_yards_after_catch",
      "receiving_first_downs",
      "receiving_epa",
      "outside_rz_targets",
      "rz_targets",
      "ez_targets",
      "ez_targets_inside_rz",
      "ez_targets_outside_rz",
      "deep_targets",
      "short_targets",
      "neutral_targets",
      "garbadge_time_targets",
      "adot",
      "catch_rate",
      "rz_catch_rate",
      "ez_catch_rate",
      "deep_catch_rate",
      "short_catch_rate",
      "receiving_yards_100",
      "receiving_yards_150",
      "receiving_yards_200",
      "receiving_tds_1",
      "receiving_tds_20",
      "receiving_tds_50",
      
      # special teams
      "special_teams_tds",
      
      # combo
      "combo_yards_100",
      "combo_yards_150",
      "touches",
      "opportunities",
      "total_yards",
      "total_tds",
      
      # fantasy
      "nw_rk",
      "nw_pts",
      "nw_pts_per",
      "nw_rk_ovr",
      "std_rk",
      "fantasy_points",
      "std_pts_per",
      "std_rk_ovr",
      "pass_pts",
      "rec_pts",
      "rush_pts",
      "st_pts",

      # snap data
      "total_snaps",
      "offense_snaps",
      "special_teams_snaps",
      "offense_snap_rate",
      "qual_snap_rate",

      # secondary info
      "player_id",
      "player_name",
      "nw_position",
      "side_of_ball"
    )
  )) %>%
  mutate(across(where(is.numeric), round, 2))
```

```{r rbs, include=FALSE}
overall_rbs <-
  overall %>%
  filter(position == "RB") %>%
  select(
    1:5, carries:rushing_tds_50,
    receptions:receiving_tds, rz_targets,
    touches:total_tds,
    nw_rk:std_rk_ovr,
    player_id, nw_position
  ) %>%
  arrange(-season, nw_rk)
```

```{r receivers, echo=FALSE}
overall_receivers <-
  overall %>%
  filter(position %in% c("WR", "TE")) %>%
  select(
    1:5, receptions:receiving_tds_50,
    nw_rk:std_rk_ovr,
    player_id, nw_position
  ) %>%
  arrange(-season, nw_rk)
```

```{r qbs, echo=FALSE}
overall_qbs <-
  overall %>%
  filter(position == "QB") %>%
  select(
    1:5, completions:int_tds,
    carries:rushing_tds, inside_ten_carries,
    nw_rk:std_rk_ovr,
    player_id, nw_position,
    -sacks, -short_attempts,
    -short_completion_pct
  ) %>% arrange(-season, player_id)

knitr::knit_exit()
```

Correlations gets weaker when filtering to quality players, need to fix
```{r Weighted opportunites}
# Weighted touches ----
weighted_opps_rbs_avg <-
  overall %>%
  filter(
    position == "RB",
    touches / games > 8
  ) %>%
  group_by(season) %>%
  mutate(
    rz_carries = rz_carries - inside_ten_carries,
    inside_ten_carries = inside_ten_carries - inside_five_carries,
    outside_rz_targets = outside_rz_targets - deep_targets
  ) %>%
  summarise(
    qual_rbs = n(),
    total_rush_pts = sum(rush_pts),
    total_carries = sum(carries),
    total_outside_rz_carries = sum(outside_rz_carries),
    total_rz_carries = sum(rz_carries),
    total_inside_ten_carries = sum(inside_ten_carries),
    total_inside_five_carries = sum(inside_five_carries),
    total_neutral_carries = sum(neutral_carries),
    total_garbadge_time_carries = sum(garbadge_time_carries),
    total_rec_pts = sum(rec_pts),
    total_targets = sum(targets),
    total_outside_rz_targets = sum(outside_rz_targets),
    total_rz_targets = sum(rz_targets),
    total_ez_targets = sum(ez_targets),
    total_deep_targets = sum(deep_targets),
    total_short_targets = sum(short_targets),
    per_carry = total_rush_pts / total_carries,
    per_outside_rz_carry = total_rush_pts / total_outside_rz_carries,
    per_rz_carry = total_rush_pts / total_rz_carries,
    per_inside_ten_carry = total_rush_pts / total_inside_ten_carries,
    per_inside_five_carry = total_rush_pts / total_inside_five_carries,
    per_neutral_carry = total_rush_pts / total_neutral_carries,
    per_garbadge_time_carry = total_rush_pts / total_garbadge_time_carries,
    per_target = total_rec_pts / total_targets,
    per_outside_rz_target = total_rec_pts / total_outside_rz_targets,
    per_rz_target = total_rec_pts / total_rz_targets,
    per_ez_target = total_rec_pts / total_ez_targets,
    per_deep_target = total_rec_pts / total_deep_targets,
    per_short_target = total_rec_pts / total_short_targets
  ) %>%
  ungroup() %>%
  summarise(
    avg_per_carry = mean(per_carry, trim = 0.05),
    avg_per_outside_rz_carry = mean(per_outside_rz_carry, trim = 0.05),
    avg_per_rz_carry = mean(per_rz_carry, trim = 0.05),
    avg_per_inside_ten_carry = mean(per_inside_ten_carry, trim = 0.05),
    avg_per_inside_five_carry = mean(per_inside_five_carry, trim = 0.05),
    avg_per_neutral_carry = mean(per_neutral_carry, trim = 0.05),
    avg_per_garbadge_time_carry = mean(per_garbadge_time_carry, trim = 0.05),
    avg_per_target = mean(per_target, trim = 0.05),
    avg_per_outside_rz_target = mean(per_outside_rz_target, trim = 0.05),
    avg_per_rz_target = mean(per_rz_target, trim = 0.05),
    avg_per_ez_target = mean(per_ez_target, trim = 0.05),
    avg_per_deep_target = mean(per_deep_target, trim = 0.05),
    avg_per_short_target = mean(per_short_target, trim = 0.05)
  )

weighted_opps_rbs <- overall %>%
  filter(position == "RB") %>%
  group_by(player_id, season) %>%
  mutate(
    rz_carries_real = rz_carries - inside_ten_carries,
    inside_ten_carries_real = inside_ten_carries - inside_five_carries,
    outside_rz_targets_real = outside_rz_targets - deep_targets,
    opps = sum(
      outside_rz_carries * weighted_opps_rbs_avg$avg_per_outside_rz_carry,
      rz_carries_real * weighted_opps_rbs_avg$avg_per_rz_carry,
      inside_ten_carries_real * weighted_opps_rbs_avg$avg_per_inside_ten_carry,
      inside_five_carries * weighted_opps_rbs_avg$avg_per_inside_five_carry,
      outside_rz_targets_real * weighted_opps_rbs_avg$avg_per_outside_rz_target,
      rz_targets * weighted_opps_rbs_avg$avg_per_rz_target,
      deep_targets * weighted_opps_rbs_avg$avg_per_deep_target
    )
  ) %>%
  group_by(season) %>%
  arrange(-opps) %>%
  mutate(
    opps_rk = 1:n(),
    efficiency = opps_rk - nw_rk
  ) %>%
  ungroup() %>%
  select(player_id, season, opps, opps_rk, efficiency)

# Weighted targets ----
weighted_opps_receivers_avg <-
  overall %>% filter(receptions / games >= 1.875, position %in% c("WR", "TE")) %>% 
  group_by(season) %>% 
  summarise(
    qual_receivers = n(),
    total_rec_pts = sum(rec_pts),
    total_targets = sum(targets),
    total_outside_rz_targets = sum(outside_rz_targets),
    total_rz_targets = sum(rz_targets),
    total_ez_targets = sum(ez_targets),
    total_ez_targets_inside_rz = sum(ez_targets_inside_rz),
    total_ez_targets_outside_rz = sum(ez_targets_outside_rz),
    total_deep_targets = sum(deep_targets),
    total_short_targets = sum(short_targets),
    total_neutral_targets = sum(neutral_targets),
    total_garbadge_time_targets = sum(garbadge_time_targets),
    per_target = total_rec_pts / total_targets,
    per_outside_rz_target = total_rec_pts / total_outside_rz_targets,
    per_rz_target = total_rec_pts / total_rz_targets,
    per_ez_target = total_rec_pts / total_ez_targets,
    per_ez_target_inside_rz = total_rec_pts / total_ez_targets_inside_rz,
    per_ez_target_outside_rz = total_rec_pts / total_ez_targets_outside_rz,
    per_deep_target = total_rec_pts / total_deep_targets,
    per_short_target = total_rec_pts / total_short_targets,
    per_neutral_target = total_rec_pts / total_neutral_targets,
    per_garbadge_time_target = total_rec_pts / total_garbadge_time_targets
  ) %>%
  ungroup() %>% 
  summarise(
    avg_per_target = mean(per_target, trim = 0.05),
    avg_per_outside_rz_target = mean(per_outside_rz_target, trim = 0.05),
    avg_per_rz_target = mean(per_rz_target, trim = 0.05),
    avg_per_ez_target = mean(per_ez_target, trim = 0.05),
    avg_per_ez_target_inside_rz = mean(per_ez_target_inside_rz, trim = 0.05),
    avg_per_ez_target_outside_rz = mean(per_ez_target_outside_rz, trim = 0.05),
    avg_per_deep_target = mean(per_deep_target, trim = 0.05),
    avg_per_short_target = mean(per_short_target, trim = 0.05),
    avg_per_neutral_target = mean(per_neutral_target, trim = 0.05),
    avg_per_garbadge_time_target = mean(per_garbadge_time_target, trim = 0.05)
  )

weighted_opps_receivers <- overall %>%
  filter(position %in% c("WR", "TE")) %>%
  group_by(player_id, season) %>%
  mutate(
    opps = sum(
      outside_rz_targets * weighted_opps_receivers_avg$avg_per_outside_rz_target,
      rz_targets * weighted_opps_receivers_avg$avg_per_rz_target,
      ez_targets_inside_rz * weighted_opps_receivers_avg$avg_per_ez_target_inside_rz,
      ez_targets_outside_rz * weighted_opps_receivers_avg$avg_per_ez_target_outside_rz,
      deep_targets * weighted_opps_receivers_avg$avg_per_deep_target,
      short_targets * weighted_opps_receivers_avg$avg_per_short_target
    )
  ) %>%
  group_by(season) %>%
  arrange(-opps) %>%
  mutate(
    opps_rk = 1:n(),
    efficiency = opps_rk - nw_rk
  ) %>%
  ungroup() %>%
  select(player_id, season, opps, opps_rk, efficiency)

# Weighted attempts ----
weighted_opps_qbs_avg <-
  overall %>% filter(position == "QB", attempts / games > 14) %>% group_by(season) %>% 
  summarise(
    qual_qbs = n(),
    total_pass_pts = sum(pass_pts),
    total_attempts = sum(attempts),
    total_outside_rz_attempts= sum(outside_rz_attempts),
    total_rz_attempts = sum(rz_attempts),
    total_ez_attempts = sum(ez_attempts),
    total_ez_attempts_inside_rz = sum(ez_attempts_inside_rz),
    total_ez_attempts_outside_rz = sum(ez_attempts_outside_rz),
    total_deep_attempts = sum(deep_attempts),
    total_short_attempts = sum(short_attempts),
    total_neutral_attempts = sum(neutral_attempts),
    total_garbadge_time_attempts = sum(garbadge_time_attempts),
    total_rush_pts = sum(rush_pts),
    total_carries = sum(carries),
    total_rz_carries = sum(rz_carries),
    per_attempt = total_pass_pts / total_attempts,
    per_outside_rz_attempt = total_pass_pts / total_outside_rz_attempts,
    per_rz_attempt = total_pass_pts / total_rz_attempts,
    per_ez_attempt = total_pass_pts / total_ez_attempts,
    per_ez_attempt_inside_rz = total_pass_pts / total_ez_attempts_inside_rz,
    per_ez_attempt_outside_rz = total_pass_pts / total_ez_attempts_outside_rz,
    per_deep_attempt = total_pass_pts / total_deep_attempts,
    per_short_attempt = total_pass_pts / total_short_attempts,
    per_neutral_attempt = total_pass_pts / total_neutral_attempts,
    per_garbadge_time_attempt = total_pass_pts / total_garbadge_time_attempts,
    per_carry = total_rush_pts / total_carries,
    per_rz_carry = total_rush_pts / total_rz_carries
  ) %>%
  ungroup() %>%
  summarise(
    avg_per_attempt = mean(per_attempt, trim = 0.2),
    avg_per_outside_rz_attempt = mean(per_outside_rz_attempt, trim = 0.2),
    avg_per_rz_attempt = mean(per_rz_attempt, trim = 0.2),
    avg_per_ez_attempt = mean(per_ez_attempt, trim = 0.2),
    avg_per_ez_attempt_inside_rz = mean(per_ez_attempt_inside_rz, trim = 0.2),
    avg_per_ez_attempt_outside_rz = mean(per_ez_attempt_outside_rz, trim = 0.2),
    avg_per_deep_attempt = mean(per_deep_attempt, trim = 0.2),
    avg_per_short_attempt = mean(per_short_attempt, trim = 0.2),
    avg_per_neutral_attempt = mean(per_neutral_attempt, trim = 0.2),
    avg_per_garbadge_time_attempt = mean(per_garbadge_time_attempt, trim = 0.2),
    avg_per_carry = mean(per_carry, trim = 0.2),
    avg_per_rz_carry = mean(per_rz_carry, trim = 0.2)
  )

weighted_opps_qbs<- overall %>%
  filter(position == "QB") %>%
  group_by(player_id, season) %>%
  mutate(
    opps = sum(
      outside_rz_attempts * weighted_opps_qbs_avg$avg_per_outside_rz_attempt,
      rz_attempts * weighted_opps_qbs_avg$avg_per_rz_attempt,
      ez_attempts_inside_rz * weighted_opps_qbs_avg$avg_per_ez_attempt_inside_rz,
      ez_attempts_outside_rz * weighted_opps_qbs_avg$avg_per_ez_attempt_outside_rz,
      deep_attempts * weighted_opps_qbs_avg$avg_per_deep_attempt,
      short_attempts * weighted_opps_qbs_avg$avg_per_short_attempt,
      neutral_attempts * weighted_opps_qbs_avg$avg_per_neutral_attempt,
      carries * weighted_opps_qbs_avg$avg_per_carry,
      rz_carries * weighted_opps_qbs_avg$avg_per_rz_carry
    )
  ) %>%
  group_by(season) %>%
  arrange(-opps) %>%
  mutate(
    opps_rk = 1:n(),
    efficiency = opps_rk - nw_rk
  ) %>%
  ungroup() %>%
  select(player_id, season, opps, opps_rk, efficiency)
```

Shares
```{r Opportunity shares}
# Raw opportunities ----
raw_opportunites <-
  weekly_cleaned %>%
  select(
    "player_id",
    1:5,
    "nw_position",
    "touches",
    "attempts",
    "neutral_attempts",
    "carries",
    "rz_carries",
    "inside_ten_carries",
    "neutral_carries",
    "targets",
    "rz_targets",
    "ez_targets",
    "neutral_targets"
  ) %>% group_by(recent_team, week, season, nw_position) %>%
  mutate(
    tm_touches = sum(touches),
    tm_attempts = sum(attempts),
    tm_neutral_attempts = sum(neutral_attempts),
    tm_carries = sum(carries),
    tm_rz_carries = sum(rz_carries, rz_targets),
    tm_inside_ten_carries = sum(inside_ten_carries),
    tm_neutral_carries = sum(neutral_carries)
  ) %>%
  group_by(recent_team, week, season) %>% 
  mutate(tm_targets = sum(targets),
    tm_rz_targets = sum(rz_targets),
    tm_ez_targets = sum(ez_targets),
    tm_neutral_targets = sum(neutral_targets)) %>% 
  arrange(recent_team, -season, week, position) %>% 
  ungroup()

# Cleaned opportunities ----
opportunites <- raw_opportunites %>%
  group_by(player_id, season) %>%
  summarise(
    full_name = last(full_name),
    recent_team = last(recent_team),
    position = last(position),
    games = n(),
    nw_position = last(nw_position),
    touches = sum(touches),
    tm_touches = sum(tm_touches),
    attempts = sum(attempts),
    tm_attempts = sum(tm_attempts),
    neutral_attempts = sum(neutral_attempts),
    tm_neutral_attempts = sum(tm_neutral_attempts),
    carries = sum(carries),
    tm_carries = sum(tm_carries),
    rz_carries = sum(rz_carries),
    tm_rz_carries = sum(tm_rz_carries),
    inside_ten_carries = sum(inside_ten_carries),
    tm_inside_ten_carries = sum(tm_inside_ten_carries),
    neutral_carries = sum(neutral_carries),
    tm_neutral_carries = sum(tm_neutral_carries),
    targets = sum(targets),
    tm_targets = sum(tm_targets),
    rz_targets = sum(rz_targets),
    tm_rz_targets = sum(tm_rz_targets),
    ez_targets = sum(ez_targets),
    tm_ez_targets = sum(tm_ez_targets),
    neutral_targets = sum(neutral_targets),
    tm_neutral_targets = sum(tm_neutral_targets),
    touch_share = sum(touches / tm_touches, na.rm = TRUE),
    attempt_share = sum(attempts / tm_attempts, na.rm = TRUE),
    neutral_attempt_share = sum(neutral_attempts / tm_neutral_attempts, na.rm = TRUE),
    carry_share = sum(carries / tm_carries, na.rm = TRUE),
    rz_carry_share = sum(rz_carries / tm_rz_carries, na.rm = TRUE),
    inside_ten_carry_share = sum(inside_ten_carries / tm_inside_ten_carries, na.rm = TRUE),
    neutral_carry_share = sum(neutral_carries / tm_neutral_carries, na.rm = TRUE),
    target_share = sum(targets / tm_targets, na.rm = TRUE),
    rz_target_share = sum(rz_targets / tm_rz_targets, na.rm = TRUE),
    ez_target_share = sum(ez_targets / tm_ez_targets, na.rm = TRUE),
    neutral_target_share = sum(neutral_targets / tm_neutral_targets, na.rm = TRUE)
  ) %>%
  mutate(across(where(is.numeric), round, 2)) %>%
  arrange(-season, recent_team, position)

# Shares ----
shares <- opportunites %>% select(1:6, 30:40, "nw_position")
```

How do metrics vary on a week-to-week basis?
```{r Coefficients of variation}
# NW pts ----
nw_pts_var <- wkly %>%
  select(player_id, season, week, nw_pts) %>%
  arrange(-season, week) %>%
  group_by(player_id, season) %>%
  summarise(across(.cols = "nw_pts", list(mean = mean, sd = sd))) %>%
  mutate(nw_pts_cv = ifelse(nw_pts_mean != 0, nw_pts_sd / nw_pts_mean, NA))

# Targets ----
target_breakdown <-
  wkly %>% ungroup() %>% group_by(player_id, season) %>% mutate(games = n()) %>% group_by(player_id, season, week) %>% 
  arrange(week) %>% 
  filter(season == 2020, position == "WR") %>% select(full_name, recent_team, position, games, targets) %>% pivot_wider(
    id_cols = c("full_name", "recent_team", "position", "games"),
    names_from = week,
    names_prefix = "W",
    values_from = targets
  ) %>% mutate(total = apply(.[(5:21)], 1, sum, na.rm = TRUE),
               first = apply(.[(5:13)], 1, sum, na.rm = TRUE)/total,
               second = apply(.[(13:21)], 1, sum, na.rm = TRUE)/total,
               std = apply(.[(5:21)], 1, sd, na.rm = TRUE),
               avg = apply(.[(5:21)], 1, mean, na.rm = TRUE),
               cv = std/avg) %>% 
  relocate(games, total, avg, cv, .after = position) %>% 
  mutate(across(where(is.numeric), round, 2)) %>% 
  filter(avg >= 5) %>% 
  arrange(recent_team, -total)

# Carries ----
carry_breakdown <-
  wkly %>% ungroup() %>% group_by(player_id, season) %>% mutate(games = n()) %>% group_by(player_id, season, week) %>% 
  arrange(week) %>% 
  filter(season == 2020, position == "RB") %>% select(full_name, recent_team, position, games, touches) %>% pivot_wider(
    id_cols = c("full_name", "recent_team", "position", "games"),
    names_from = week,
    names_prefix = "W",
    values_from = touches
  ) %>% mutate(total = apply(.[(5:21)], 1, sum, na.rm = TRUE),
               first = apply(.[(5:13)], 1, sum, na.rm = TRUE)/total,
               second = apply(.[(13:21)], 1, sum, na.rm = TRUE)/total,
               std = apply(.[(5:21)], 1, sd, na.rm = TRUE),
               avg = apply(.[(5:21)], 1, mean, na.rm = TRUE),
               cv = std/avg) %>% 
  relocate(games, total, avg, cv, .after = position) %>% 
  mutate(across(where(is.numeric), round, 2)) %>% 
  filter(avg >= 8) %>% 
  arrange(recent_team, -total)
```

When ready to join added variables to subset tables, run this
```{r eval=FALSE, include=FALSE}
# Join weighted opportunities to subset tables
overall_rbs <- overall_rbs %>% left_join(weighted_opps_rbs, by = c("player_id", "season"))
overall_receivers <- overall_receivers %>% left_join(weighted_opps_receivers, by = c("player_id", "season"))
overall_qbs <- overall_qbs %>% left_join(weighted_opps_qbs, by = c("player_id", "season"))
```

```{r NW team pts}
nw_team_pts <- games %>%
  filter(season <= 2020) %>%
  group_by(season, team) %>%
  mutate(position = ifelse(sum(team_result) >= 0, 'OFF', 'DEF')) %>%
  summarise(
    position = last(position),
    nw_pts = abs(sum(team_result)),
    mean = abs(mean(team_result)),
    sd = abs(sd(team_result)),
    cv = mean / sd
  ) %>%
  arrange(-nw_pts) %>%
  group_by(season) %>%
  mutate(nw_rk = 1:n(),
                across(where(is.numeric), round, 2)) %>%
  relocate(nw_rk, .before = season) %>%
  arrange(-season, nw_rk)
```

```{r Export season and weekly stats to csv files}
write_csv(weekly_joined, "weekly_joined.csv")
write_csv(overall_joined, "overall_joined.csv")

write_csv(wkly, "weekly_stats.csv")
write_csv(season, "season_stats.csv")
write_csv(rosters, "rosters.csv")
```

```{r ADP}
overall_joined_adp <- overall %>%
  filter(side_of_ball == "OFF") %>% 
  left_join(adp_historic, by = c("season", "player_id"))

baseline_qb <-
  overall_joined_adp %>%
  group_by(season, nw_position) %>%
  filter(position == "QB", nw_rk <= 25) %>%
  arrange(-nw_pts) %>%
  summarise(
    baseline = last(nw_pts),
    avg = mean(nw_pts)
  )

baseline_rb <-
  overall_joined_adp %>%
  group_by(season, nw_position) %>%
  filter(position == "RB", nw_rk <= 53) %>%
  arrange(-nw_pts) %>%
  summarise(
    baseline = last(nw_pts),
    avg = mean(nw_pts)
  )

baseline_rec <-
  overall_joined_adp %>%
  group_by(season, nw_position) %>%
  filter(nw_position == "WR/TE", nw_rk <= 56) %>%
  arrange(-nw_pts) %>%
  summarise(
    baseline = last(nw_pts),
    avg = mean(nw_pts)
  )

overall_joined_adp %>%
  group_by(nw_position, season) %>%
  filter(nw_rk <= 10) %>% 
  group_by(nw_position) %>% 
  summarise(avg_adp = mean(overall, na.rm = TRUE),
            high_adp = quantile(overall, probs = 0.75, na.rm = TRUE),
            low_adp = quantile(overall, probs = 0.75, na.rm = TRUE),
            avg_touches = mean(touches),
            avg_touches_per = mean(touches / games),
            avg_nw_pts = mean(nw_pts),
            avg_nw_pts_per = mean(nw_pts_per))

nw_vos <- overall_joined_adp %>%
  filter(position == "QB", nw_rk == 10) %>%
  bind_rows(
    overall_joined_adp %>%
      filter(position %in% c("RB", "WR", "TE"), nw_rk == 30)
  ) %>%
  arrange(position, -season) %>%
  select(season, nw_position, nw_pts) %>%
  rename(vos_nw = nw_pts)

nw_voa <- overall_joined_adp %>%
  filter(position == "QB", nw_rk == 24) %>%
  bind_rows(
    overall_joined_adp %>%
      filter(position %in% c("RB", "WR", "TE"), nw_rk == 60)
  ) %>%
  arrange(position, -season) %>%
  select(season, nw_position, nw_pts) %>%
  rename(voa_nw = nw_pts)

nw_vor <- overall_joined_adp %>%
  filter(position == "QB", nw_rk == 25) %>%
  bind_rows(
    overall_joined_adp %>%
      filter(nw_position == "WR/TE", nw_rk == 56)
  ) %>%
  bind_rows(
    overall_joined_adp %>%
      filter(nw_position == "RB", nw_rk == 53)
  ) %>%
  arrange(position, -season) %>%
  select(season, nw_position, nw_pts) %>%
  rename(vor_nw = nw_pts)

nw_value <- nw_vos %>%
  left_join(nw_voa, by = c("season", "nw_position")) %>%
  left_join(nw_vor, by = c("season", "nw_position"))

std_vos <- overall_joined_adp %>%
  filter(position == "QB", std_rk == 10) %>%
  bind_rows(
    overall_joined_adp %>%
      filter(position %in% c("RB", "WR", "TE"), std_rk == 30)
  ) %>%
  arrange(position, -season) %>%
  select(season, nw_position, fantasy_points) %>%
  rename(vos_std = fantasy_points)

std_voa <- overall_joined_adp %>%
  filter(position == "QB", std_rk == 24) %>%
  bind_rows(
    overall_joined_adp %>%
      filter(position %in% c("RB", "WR", "TE"), std_rk == 60)
  ) %>%
  arrange(position, -season) %>%
  select(season, nw_position, fantasy_points) %>%
  rename(voa_std = fantasy_points)

std_vor <- overall_joined_adp %>%
  filter(position == "QB", std_rk == 25) %>%
  bind_rows(
    overall_joined_adp %>%
      filter(nw_position == "WR/TE", std_rk == 56)
  ) %>%
  bind_rows(
    overall_joined_adp %>%
      filter(nw_position == "RB", std_rk == 53)
  ) %>%
  arrange(position, -season) %>%
  select(season, nw_position, fantasy_points) %>%
  rename(vor_std = fantasy_points)

std_value <- std_vos %>%
  left_join(std_voa, by = c("season", "nw_position")) %>%
  left_join(std_vor, by = c("season", "nw_position"))

value <- nw_value %>%
  left_join(std_value, by = c("season", "nw_position")) %>%
  mutate(across(where(is.numeric), round, 0))

player_values <- overall %>%
  select(1:5, player_id, nw_position, nw_pts, nw_rk, fantasy_points, std_rk) %>%
  left_join(value, by = c("season", "nw_position")) %>%
  group_by(player_id, season) %>%
  summarise(
    full_name = last(full_name),
    recent_team = last(recent_team),
    position = last(position),
    vos_nw = nw_pts - vos_nw,
    vos_std = fantasy_points - vos_std,
    vor_nw = nw_pts - vor_nw,
    vor_std = fantasy_points - vor_std
  )

proj <- overall %>%
  filter(position %in% c("QB", "RB", "WR", "TE"), season == 2020) %>%
  left_join(adp_2021 %>% select(-season), by = c("player_id")) %>%
  mutate(
    nw_pts_per = nw_pts / games,
    across(where(is.numeric), round, 2)
  ) %>%
  filter(!is.na(pick)) %>%
  arrange(pick)

rb_proj <- proj %>%
  filter(position == "RB") %>%
  mutate(
    nw_vor = nw_pts - 45,
    std_vor = fantasy_points
  ) %>%
  select(
    pick, 2:5,
    nw_pts, fantasy_points, nw_pts_per,
    nw_rk_ovr, std_rk_ovr,
    carries:rushing_tds_50
  )
%>% 

rb_2020_vor <- proj %>% filter(position == "RB", std_rk >= 50) %>% select(std_rk, fantasy_points)
```

Working with RB data
```{r}
library(ggplot2)
library(ggrepel)
library(ggExtra)

adp_historic <- read_csv("./data/adp_historic.csv") %>%
  select(season, player_id, sleeper_id, pick, overall:n)
adp_2021 <- read_csv("./data/adp_2021.csv") %>%
  select(season, player_id, sleeper_id, pick, overall:n)

overall_rbs %>% left_join(adp_historic, by = c("season", "player_id")) %>%
  group_by(nw_position, season) %>%
  filter(nw_rk <= 10) %>% 
  group_by(nw_position) %>% 
  summarise(avg_adp = mean(overall, na.rm = TRUE),
            high_adp = quantile(overall, probs = 0.75, na.rm = TRUE),
            low_adp = quantile(overall, probs = 0.75, na.rm = TRUE),
            avg_touches = mean(touches),
            avg_touches_per = mean(touches / games),
            avg_nw_pts = mean(nw_pts),
            avg_nw_pts_per = mean(nw_pts_per))

overall_rbs2 <- overall_rbs %>% 
  left_join(adp_historic, by = c("season", "player_id")) %>%
  mutate(pick = ifelse(is.na(pick), 16, pick)) %>% 
  group_by(nw_position, season)

ggplot(overall_rbs2, aes(x=pick, y=nw_pts, label=full_name)) +
    geom_point(shape=1) + 
    geom_smooth(method=loess) + 
  scale_x_continuous(breaks=seq(0, 14, 1)) + 
geom_text_repel(data=subset(overall_rbs2, pick >= 9 & nw_pts >= 200))

overall2 <- overall %>% 
  filter(position %in% c("QB", "RB", "WR", "TE")) %>% 
  left_join(adp_historic, by = c("season", "player_id")) %>%
  mutate(pick = ifelse(is.na(pick), 16, pick)) %>% 
  group_by(nw_position, season)

ggplot(overall2 %>% filter(position == "QB", pick <= 10, season >= 2017), aes(x=pick, y=nw_pts, color=season)) +
      geom_point() +
  scale_x_continuous(breaks=seq(0, 16, 1))
```

QB 2021 Week 1 matchups
```{r}
average_qbs <-
  weekly_joined %>%
  filter(position == "QB", n() > 1) %>%
  group_by(player_id, season) %>%
  summarise(across(
    .cols = c(
      completions:int_tds,
      carries:rushing_tds,
      inside_ten_carries,
      nw_pts,
      fantasy_points
    ),
    .fns = mean,
    na.rm = TRUE,
    .names = "{.col}_per"
  )) %>%
  mutate(across(where(is.numeric), round, 2))

average_rbs <-
  weekly %>%
  filter(nw_position == "RB", n() > 1) %>%
  group_by(player_id, season) %>%
  summarise(across(
    .cols = c(
      carries:receiving_tds,
      rz_targets,
      touches:combo_yards_150,
      total_snaps:nw_pts,
      fantasy_points
    ),
    .fns = mean,
    na.rm = TRUE,
    .names = "{.col}_per"
  )) %>%
  mutate(across(where(is.numeric), round, 2))

overall_qbs3 <-
  overall %>%
  filter(position == "QB", n() > 1, season == 2020) %>%
  select(player_id, 1:5, nw_rk) %>%
  left_join(overall_qbs2, by = c("player_id", "season")) %>%
  relocate(player_id, .after = last_col()) %>%
  relocate(nw_rk, .before = 1) %>%
  arrange(nw_rk)


games %>% select(game_id, location, team, opp)

week_1 <-
  games_21 %>% filter(week == 1) %>% select(location, team, opp)

allowed_20 <-
  fpts_allowed %>% filter(season == 2020) %>% select(opp = opponent, position, per) %>%
  arrange(-per) %>%
  mutate(rk = 1:n())

joined_qbs_week_1 <-
  overall_qbs3 %>% left_join(week_1, by = c("recent_team" = "team")) %>% left_join(allowed_20, by = c("opp", "position"))

%>% 

overall_qbs2 <-
  weekly %>%
  filter(position == "QB", n() > 1) %>%



overall_qbs2 <-
  overall %>%
  filter(position == "QB") %>%
  select(
  ) %>%
  arrange(-season, nw_rk)
```

